### ISSUE TITLE
Add PUID and PGID settings

### ISSUE THREAD

**Issue by DDS-ALL** [RanKKI/Bangumi#13]
Since the user I use by default is not the `root` user, I want Bangumi to support `PUID` and `PGID` settings so that Bangumi generates a profile that corresponds to the user I am using

I can also write the code myself and pull requests if the author needs help

**Comment by RanKKI** [comment]
Yeah, feels free to edit it!
I'm not an expert on Linux so I'm not very sure which part you want to change.

So, please make a PR ~

**Comment by DDS-ALL** [comment]
Okay, I'll finish the `Dockerfile` changes in the next few days and PR
