### ISSUE TITLE
add pikpak as a downloader

### ISSUE THREAD

**Issue by Wsine** [RanKKI/Bangumi#9]
I thought this idea works and wanna turn to you whether it is feasible.

pikpak is a webdrive providing magnet and torrent download feature. thus, i think it is possible to implement as a kind of downloader in this project.

the related api is also summaried in another project already:  https://github.com/Quan666/PikPakAPI

I kindly request for your help to review the feasibility please and wonder whether you have time to implement it or if you can briefly give directions which files I should pay attention to for modification.

Sincerely

**Comment by RanKKI** [comment]
Hi, Wsine

You can have a look at the folder [here](https://github.com/RanKKI/Bangumi/tree/main/bangumi/downloader),  as long as you extend/implement the Downloader class (in the file `downloader.py`)  and register the new downloader in the `__init__.py`. 

No need to change other files.

by the way, the main loop will move the finished files to the media folder, I don't think Pikpak supported it, so you may always return an empty list of the `get_downloads` method.

feels free to modify this project and PR is welcome xD

**Comment by Wsine** [comment]
Thanks for the tips. I will try to approach it and may consult you occasionally.
